# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7249a47aa090a7cf137ae5e0bd2a856f2f53a899e9bee1f86a9f873d463c93d3a0e86b7704f680c0b4005c1fa3973e902175e47379e59f820ba7178913c0482f

test:
  secret_key_base: 5dbef634bc2684d9391aac32dbe1e9bb40abe1f7d34a6ae3de0ba181c7377ea32a5264a15d5a8129e6e98bedbd5fc695c229d2d7d627a5245e9ad57c18af1a83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
